# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-18 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import paypaladaptive.models


class Migration(migrations.Migration):

    dependencies = [
        ('paypaladaptive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preapproval',
            name='valid_until_date',
            field=models.DateTimeField(default=paypaladaptive.models.default_valid_date, verbose_name='valid until'),
        ),
    ]
